/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLayout: typeof import('./src/components/layout/AppLayout.vue')['default']
    ChatAvatar: typeof import('./src/components/chat/ChatAvatar.vue')['default']
    ChatEmptyState: typeof import('./src/components/chat/ChatEmptyState.vue')['default']
    ChatMessage: typeof import('./src/components/chat/ChatMessage.vue')['default']
    NicknameDialog: typeof import('./src/components/chat/NicknameDialog.vue')['default']
    ReminderForm: typeof import('./src/components/reminder/ReminderForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SetupWizard: typeof import('./src/components/setup/SetupWizard.vue')['default']
    Sidebar: typeof import('./src/components/layout/Sidebar.vue')['default']
    SkillForm: typeof import('./src/components/skill/SkillForm.vue')['default']
    SkillsTabContent: typeof import('./src/components/skill/SkillsTabContent.vue')['default']
    TitleBar: typeof import('./src/components/layout/TitleBar.vue')['default']
    UnlockDialog: typeof import('./src/components/setup/UnlockDialog.vue')['default']
  }
}
